services:
    codehorizon:
        container_name: codehorizon
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5000:8080'
        env_file:
            - .env
        restart: always
        depends_on:
            - redis

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '127.0.0.1:6379:6379'
        restart: always
