name: Kotlin Spring Boot CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: temurin

      - name: Create .env file
        run: |
          echo "DOMAIN_URL=${{ secrets.DOMAIN_URL }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "R2_ACCESS_KEY=${{ secrets.R2_ACCESS_KEY }}" >> .env
          echo "R2_ENDPOINT=${{ secrets.R2_ENDPOINT }}" >> .env
          echo "R2_SECRET_KEY=${{ secrets.R2_SECRET_KEY }}" >> .env
          echo "YANDEX_APP_PASSWORD=${{ secrets.YANDEX_APP_PASSWORD }}" >> .env
          echo "YANDEX_USERNAME=${{ secrets.YANDEX_USERNAME }}" >> .env
          echo "FRONT_DOMAIN_URL=${{ secrets.FRONT_DOMAIN_URL }}" >> .env

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd work/codehorizon-api/ && git pull && docker compose up -d --build"